name: Build AndroidPtraceInject (Using build.sh)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r26b
      BUILD_DIR: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK (required by NDK build system)
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake unzip

    - name: Download and unzip Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip
        unzip android-ndk-${ANDROID_NDK_VERSION}-linux.zip
        echo "ANDROID_NDK=$GITHUB_WORKSPACE/android-ndk-${ANDROID_NDK_VERSION}" >> $GITHUB_ENV

    - name: Remove hardcoded ANDROID_NDK and TOOLCHAIN_FILE from CMakeLists.txt
      run: |
        sed -i '/set(ANDROID_NDK/d' CMakeLists.txt
        sed -i '/set(CMAKE_TOOLCHAIN_FILE/d' CMakeLists.txt

    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Run build.sh script to build all ABIs
      run: |
        ./build.sh
      env:
        ANDROID_NDK: ${{ env.ANDROID_NDK }}

    - name: Show build output files
      run: |
        find output/ -type f || echo "No output directory or files found."

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-ptrace-inject-artifacts
        path: output/
